name: Deploy Multilingual Site

on:
  release:
    types: [published]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.TOKEN }}
            publish_dir: .
            publish_branch: gh-pages
            keep_files: true
            destination_dir: ./v${{ github.ref_name }}
        - name: Artifact
          uses: actions/upload-artifact@v4
          with:
           name: Site
           path: .
        - name: Generate Link
          run: |
           echo "Site link: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/v${{ github.ref_name }}"

         
